### ISSUE TITLE
Integrate a bcoin SVP into lotion app.js

### ISSUE THREAD

**Issue by cbonoz** [CosmicBridge/server#3]
Requires #2 , integrate bcoin such that batched payments can be distributed.

**Comment by lidarwin** [comment]
The bcoin SVP should be able to run alongside the lotion app.js.
We need:
1) Function that takes in a bitcoin transaction hash and returns the number of verifications
2) Function that takes in a bitcoin transaction hash and returns the public key of the payer's bitcoin public address
3) Function that takes in a bitcoin transaction hash and returns the receiver's public key

Eventually, to accommodate [Issue #3](https://github.com/CosmicBridge/wallet/issues/3) in CosmicBridge/wallet, we will need:

4) Function that takes in a bitcoin public address (of a payer) and a bitcoin signature and verifies that they match.

**Comment by itamarro** [comment]
Still applicable? Or may I close this?

**Comment by cbonoz** [comment]
completed, payments from the multisig master is remaining task
